@url = http://localhost:3003/api/blogs

GET {{url}}

###
POST {{url}}
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im11aWtrdWtvb2RhYSIsImlkIjoiNWU5MjAyNWIyYTkzNzg1NGNkMDg1YTUxIiwiaWF0IjoxNTg2Njg0ODQyfQ.bA5V8k32yYC3K5DwtKto4o-0fjst4D8KekIqHXyX8p0

{
    "title": "This must be deleted.",
    "author": "Muikku",
    "url": "https://fullstackopen.com/osa4/sovelluksen_rakenne_ja_testauksen_alkeet",
    "likes": 508,
    "userId": "5e92025b2a937854cd085a51"
}

###

DELETE {{url}}/5e91a0d4716c4641f9c82977

###
PUT {{url}}/5e8f558073c43d5643ea01de
Content-Type: application/json

{
    "title": "Testing is very nice.",
    "author": "Muikku",
    "url": "https://fullstackopen.com/osa4/sovelluksen_rakenne_ja_testauksen_alkeet",
    "likes": 5099
}