GET HTTP://localhost:3001/api/diagnoses

###

GET HTTP://localhost:3001/api/patients

###
GET HTTP://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667

###
POST HTTP://localhost:3001/api/patients
content-type: application/json

{
      "name": "Darth Weaver",
      "dateOfBirth": "1931-04-09",
      "ssn": "090431-8xxx",
      "gender": "female",
      "occupation": "Alien-Sith Abomination"
}
###
POST HTTP://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
content-type: application/json

{
  "date": "2019-08-05",
  "type": "HealthCheck",
  "specialist": "MD Mouse",
  "employerName": "HyPD",
  "diagnosisCodes": ["Z57.1", "Z74.3", "M51.2"],
  "description": "Patient mistakenly found himself in a nuclear plant waste site without protection gear. Very minor radiation poisoning. ",
  "healthCheckRating": 832
}